### ISSUE TITLE
Serializing speckle props needs some help

### ISSUE THREAD

**Issue by haitheredavid** [sasakiassociates/speckle-unity-core#1]
### info 
When pulling a commit down from speckle it currently stores it's props in the `SpeckleProperties` object. When this happens there is a huge thread block and takes way to long to store and move onto conversion. Maybe setting the props as a task would help or wrap the whole command as an async one? 

### todo
- [ ] Make Setting Props `awaitable`
- [ ] Test for what props needs to be stored
- [ ] Optimize how props are accessed
