### ISSUE TITLE
Editor support for Speckle node object 

### ISSUE THREAD

**Issue by haitheredavid** [sasakiassociates/speckle-unity-core#2]
### info 
Create a cleaner interface for visualizing all the objects being structured for a commit. I would like to avoid creating a game object when it's not necessary. The layers or groups that come in from the commit object need to be constructed, editable, and deconstructed back into a speckle object.... and this isn't really defined yet. So hopefully setting up some sort of editor for throwing together an commit / reference object for speckle will be helpful.

### todo 
- [ ] Support basic list structure 
- [ ] Support tree structures
- [ ] Support re-arranging structure
- [ ] Maybe be able to change structure?
